### PR TITLE
NU5 support

### PR DESCRIPTION
**Pull request by nighthawk24**

### CODE REVIEW

**Comment by conradoplg** [comment]
Cool, I was just looking for this! I tried building for testnet and launching it but I get a dialog with

> Unfortunately, the Rust libraries are missing and the only remedy is to update to a new version. (Note to developers: try commenting out mavenLocal)

(Sorry if it's something silly, it's my first time building the project)

**Comment by nighthawk24** [comment]
> Cool, I was just looking for this! I tried building for testnet and launching it but I get a dialog with
> 
> > Unfortunately, the Rust libraries are missing and the only remedy is to update to a new version. (Note to developers: try commenting out mavenLocal)
> 
> (Sorry if it's something silly, it's my first time building the project)

Hey Conrado, Test-net support was recently fixed and we haven't tried it. Our focus now is to ship the NU5 support, and then we can review the test-net setup.

**Comment by Mandeepbhalothia** [comment]
> Cool, I was just looking for this! I tried building for testnet and launching it but I get a dialog with
> 
> > Unfortunately, the Rust libraries are missing and the only remedy is to update to a new version. (Note to developers: try commenting out mavenLocal)
> 
> (Sorry if it's something silly, it's my first time building the project)

@conradoplg Can you please try by clean and rebuild project/sync with gradle files

**Comment by conradoplg** [comment]
> > Cool, I was just looking for this! I tried building for testnet and launching it but I get a dialog with
> > > Unfortunately, the Rust libraries are missing and the only remedy is to update to a new version. (Note to developers: try commenting out mavenLocal)
> > 
> > 
> > (Sorry if it's something silly, it's my first time building the project)
> 
> @conradoplg Can you please try by clean and rebuild project/sync with gradle files

I did that and got the same error. Then I realized that maybe the reason was that I was trying to use a virtual device. Using my phone worked. I also managed to test in on testnet and everything seems to work :tada:

**Pull request merged**
